### PR TITLE
migration from colivre themes repository to cirandas. Following themes...

### PR DESCRIPTION
**Pull request by melissawen**
...were transfered and fixed their symbolic links: accn, adocci, amevf, aporba, ascoma, ascoob, canjerana, colibris, coofe, coopaed, coopercorte, coopertane, ecosoltur, faces-do-brasil, rango-vegan, rede-ostra, verde-arte, yaya

### CODE REVIEW

**Comment by brauliobo** [comment]
melissa, I see some themes from colivre-themes not present: `apemmar, `cidade-nova`, `new-apemmar`, `terra-mirim` and `terra-mirim-old`

**Comment by brauliobo** [comment]
cc @joenio

**Comment by brauliobo** [comment]
@melissawen waiting for them to pull on the server.

**Comment by brauliobo** [comment]
`ascoob` doesn't have a `owner_id`, so it cannot be used, can I remove it?

**Comment by brauliobo** [comment]
`accn` use an invalid owner_id

**Comment by brauliobo** [comment]
please remove obsolete themes

**Comment by melissawen** [comment]
Hi @brauliobo ! I submmited a new merge with the following corrections: recent version of ascoob, fix owner_id of accn and add new-apemmar and terra-mirim. The themes apemmar, terra-mirim-old and cidade-nova are obsoletes, so I didn't import to here.

**Comment by brauliobo** [comment]
hi @melissawen! so, `apemmar`, `cidade-nova`, and `terra-mirim-old` are not used anymore?

**Pull request merged**
